version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeperData:/opt/zookeeper-3.4.9/data
  kafka:
    image: wurstmeister/kafka:0.10.1.0-2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /kafka/broker-1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.102
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafkaData:/kafka